### ISSUE TITLE
CircularImageView has no size until it draws itself

### ISSUE THREAD

**Issue by bsegall** [siyamed/android-shape-imageview#13]
It's using a fixed width and height, but in the editor it has width/height of 0. At runtime, it has width/height of 0 until it draws something. This is a problem because it's in a RelativeLayout and other views are aligned to it, which makes them shift in front of you.

I looked at the onMeasure code and I can't see why this happens.

I am settings its content with Picasso, but that shouldn't matter - the size is fixed so it should never be getting resized.

<com.github.siyamed.shapeimageview.CircularImageView
        android:id="@+id/user_photo_image_view"
        android:layout_width="66dp"
        android:layout_height="66dp"
        />

My workaround is to put it inside of a LinearLayout that has a fixed size.

**Comment by siyamed** [comment]
I am sorry I tried and couldn't replicate the problem.

**Comment by siyamed** [comment]
actually this is the same as #19 I will continue checking it.
