### ISSUE TITLE
How to Rotate Hexagon shape?

### ISSUE THREAD

**Issue by oalpayli** [siyamed/android-shape-imageview#15]
I would like to rotate hexagon shape for my design. You can just consider your svg that rotates 90 angle. How can I make this? Please help me....

**Comment by oalpayli** [comment]
Sorry my bad. I found it my way. :)

**Comment by donchakkappan** [comment]
Could you please share the solution

**Comment by ramprasath23** [comment]
hi please share if you have any solution for this
