### ISSUE TITLE
Error on running

### ISSUE THREAD

**Issue by tellfa** [siyamed/android-shape-imageview#16]
hi, i can't use this your project in Android Studio 1.1
image has attached. please check and help me :)
tnx dear friend

![scaleimage_gradle_eroor](https://cloud.githubusercontent.com/assets/10583945/6125113/cd82e958-b0c7-11e4-95f1-300bd897b1ed.PNG)

**Comment by StefMa** [comment]
You can fix this to avoid using + :)
So use
```java
compile 'com.github.siyamed:android-shape-imageview:0.9.2@aar'
```

**Comment by siyamed** [comment]
thanks again @StefMa :)
