### ISSUE TITLE
The widget can't work well in the RelativeLayout

### ISSUE THREAD

**Issue by zsigui** [siyamed/android-shape-imageview#19]
When I used ithe CircularImageView in the RelativeLayout, I found I can't define the size of the view with fixed dp which work well in the LinearLayout. Can't it be fit?

**Comment by siyamed** [comment]
@zsigui can you please send me a non-working example with relative layout ?

**Comment by zsigui** [comment]
Sorry, I forgot. 
![image 4](https://cloud.githubusercontent.com/assets/5293511/6991158/8d965b54-dab6-11e4-95b3-65b909f8ee77.png)
 ( In LinearLayout, width and height all 100dp)
![image 3](https://cloud.githubusercontent.com/assets/5293511/6991141/bd6c4b5a-dab5-11e4-93e8-e5e714ed5167.png) ( In RelativeLayout, width and height all 100dp)
It shows like above. They all set the same configure:
```xml
<com.github.siyamed.shapeimageview.CircularImageView
			android:id="@+id/ivPortrait"
			android:layout_width = "100dp"
			android:layout_height = "100dp"
			android:layout_marginTop="20dp"
			android:layout_centerInParent="true"
			android:scaleType="centerCrop"
			android:alpha="1"
			app:siBorderColor="@color/material_blue_grey_800"
			app:siBorderWidth="3dp"
			android:src="@android:drawable/ic_dialog_map"/>
```
By the way, the border of pic seems to be covered by the picture

**Comment by LeeeYou** [comment]
i have the same problem , however i put "CircularImageView" into LinearLayout , it's work ok .
anyway ,thanks
