### ISSUE TITLE
CenterInside not working with pentagonImageView

### ISSUE THREAD

**Issue by cgomezmendez** [siyamed/android-shape-imageview#21]
I have an image with scaletype centerInside but isn't working, i have this:
<com.github.siyamed.shapeimageview.PentagonImageView
            android:layout_width="match_parent"
            android:layout_height="75dp"
            android:src="@drawable/restaurant"
            android:scaleType="centerInside"
            />

**Comment by siyamed** [comment]
I think we cant centerInside? it should be centercrop since I am cropping the image according to the mask. center inside will mean no mask ?
