### ISSUE TITLE
License

### ISSUE THREAD

**Issue by izotx** [siyamed/android-shape-imageview#32]
Siyamed, thank you for great library. I would love to use in my project but I have a small problem with your license. 

Apache License 2.0 standard legal line typically begins with:
Copyright {yyyy} {name of copyright owner}
In the case of your  Android-ShapeImageView, only the subsequent “Licensed under the Apache License, Version 2.0 ...” is listed without any copyright owner preceding it. 

Would you mind adding your copyright information to it? 
thank you,
Janusz

**Comment by siyamed** [comment]
Thanks for the heads up. 
I wasnt even aware Apache was copy-right. I will change that line now and maybe later find a less restricting license. Please use and modify it as you like.

**Comment by siyamed** [comment]
changed it into MIT license. (http://choosealicense.com/ told me that it is the most permissive) @izotx

**Comment by izotx** [comment]
You are the best @siyamed . Thanks a lot!
