### ISSUE TITLE
What is the Latest version of this Library?

### ISSUE THREAD

**Issue by iAviatorJose** [siyamed/android-shape-imageview#34]
Your library is very useful. Thank You.

The version as seen in the below statement is 0.9+ and android studio throws a warning for such statements.
compile 'com.github.siyamed:android-shape-imageview:0.9.+@aar'

Can you tell me whats the new version is ??

**Comment by StefMa** [comment]
Hey @iAviatorJose 

take a look at the [README](https://github.com/siyamed/android-shape-imageview/blob/master/README.md).
Under the "title" you see some badges. One is maven central. It shows your version number ;)

**Comment by iAviatorJose** [comment]
@StefMa thank you
