### ISSUE TITLE
Black line when roundedimageview used issue

### ISSUE THREAD

**Issue by hellsayenci** [siyamed/android-shape-imageview#35]
hi,
great library thanks for all of it. I have an issue when I try to use your roundedimageview view. This is my xml define : 
<com.github.siyamed.shapeimageview.RoundedImageView
                        android:id="@+id/iv_message_image"
                        android:layout_width="250dp"
                        android:layout_height="match_parent"
                        android:contentDescription="@string/app_name"
                        android:scaleType="fitXY"
                        app:siRadius="11dp"
                        app:siBorderWidth="2dp"
                        android:padding="1dp"
                        app:siBorderColor="@color/chat_bubble_green"
                        app:siSquare="true"
                        android:src="@drawable/profile" />

In the top layout I have a linearlayout which has a 9 png as background. Anyway this implementation is in a recyclerview. And some items in that view some of the roundedimageview's side have black line. This is what I want to mean : 
![issue](https://cloud.githubusercontent.com/assets/11094251/11033909/de92052c-86ef-11e5-9efe-db6f7426708f.png)

Any ideas? Thanks...

**Comment by AcumenDev** [comment]
Hi, problem similar, the decision wasn't found?

**Comment by nikunjparadva** [comment]
I face same isuue any sollution?
