### ISSUE TITLE
Zoom in/out not working

### ISSUE THREAD

**Issue by rajscet** [siyamed/android-shape-imageview#50]
Hello.

Zoom In/out not working. what should be wrong?
Same code working with normal ImageView.

**Comment by siyamed** [comment]
I think something changed in the framework. scaling is probably wrong

**Comment by rajscet** [comment]
I found follwoing link at least zoom in/out working..

https://github.com/MikeOrtiz/TouchImageView/pull/101/commits/84e04d2425a143badabf4e2513f91a25536d5fa2

**Comment by siyamed** [comment]
👍🏾
